import type { Course, CourseCategory } from "./types";

export const courseCategories: CourseCategory[] = [
  { id: "all", label: "همه دوره‌ها" },
  { id: "speaking", label: "فن بیان" },
  { id: "presentation", label: "ارائه و سخنرانی" },
  { id: "communication", label: "ارتباط مؤثر" },
  { id: "voice", label: "آواسازی و صدا" },
];

/**
 * Featured course catalog for section #5.
 * Six structured courses spanning the academy's main tracks.
 */
export const courses: Course[] = [
  {
    id: "fundamentals",
    title: "مبانی فن بیان",
    subtitle: "از صفر تا تسلط بر صحبت کردن در جمع",
    category: "speaking",
    level: "مقدماتی",
    mentor: "دکتر سارا محمدی",
    mentorInitial: "س",
    rating: 4.9,
    reviews: 2148,
    durationHours: 18,
    lessons: 64,
    price: 850000,
    originalPrice: 1200000,
    bestseller: true,
    accent: "violet",
    glyph: "🎤",
  },
  {
    id: "presentation-mastery",
    title: "استاد ارائه‌دهنده",
    subtitle: "ساخت و اجرای ارائه‌های تأثیرگذار",
    category: "presentation",
    level: "متوسط",
    mentor: "مهندس رضا کریمی",
    mentorInitial: "ر",
    rating: 4.8,
    reviews: 1567,
    durationHours: 24,
    lessons: 82,
    price: 1200000,
    bestseller: true,
    accent: "pink",
    glyph: "📊",
  },
  {
    id: "voice-training",
    title: "آواسازی حرفه‌ای صدا",
    subtitle: "تکنیک‌های تنفسی و رسایی صدای جذاب",
    category: "voice",
    level: "متوسط",
    mentor: "استاد نگار احمدی",
    mentorInitial: "ن",
    rating: 4.9,
    reviews: 932,
    durationHours: 16,
    lessons: 48,
    price: 980000,
    accent: "orchid",
    glyph: "🎙️",
  },
  {
    id: "effective-communication",
    title: "ارتباط مؤثر در محیط کار",
    subtitle: "مهارت‌های کلامی برای پیشرفت شغلی",
    category: "communication",
    level: "متوسط",
    mentor: "دکتر امیر حسینی",
    mentorInitial: "ا",
    rating: 4.7,
    reviews: 1203,
    durationHours: 20,
    lessons: 70,
    price: 1100000,
    originalPrice: 1400000,
    accent: "blue",
    glyph: "🤝",
  },
  {
    id: "leadership-speaking",
    title: "سخنوری رهبران",
    subtitle: "هوش هیجانی و اقناع در رهبری",
    category: "speaking",
    level: "پیشرفته",
    mentor: "دکتر سارا محمدی",
    mentorInitial: "س",
    rating: 5.0,
    reviews: 645,
    durationHours: 28,
    lessons: 96,
    price: 1650000,
    accent: "amber",
    glyph: "👑",
  },
  {
    id: "storytelling",
    title: "هنر داستان‌گویی",
    subtitle: "ساختن روایت‌هایی که می‌مانند",
    category: "presentation",
    level: "حرفه‌ای",
    mentor: "استاد نگار احمدی",
    mentorInitial: "ن",
    rating: 4.8,
    reviews: 814,
    durationHours: 22,
    lessons: 58,
    price: null,
    accent: "pink",
    glyph: "📖",
  },
];

export const accentClasses: Record<Course["accent"], string> = {
  violet: "from-blue-600/25 to-blue-400/5 text-blue-600",
  pink: "from-amber-300/25 to-amber-100/5 text-amber-600",
  orchid: "from-sky-400/25 to-sky-200/5 text-sky-600",
  amber: "from-amber-200/40 to-amber-100/5 text-amber-600",
  blue: "from-blue-200/40 to-blue-100/5 text-blue-600",
};
