import type { CourseDetail } from "./types";

/**
 * Full course detail — English lessons for school students.
 * Ids match homepage catalog.
 */
export const courseDetails: Record<string, CourseDetail> = {
  fundamentals: {
    id: "fundamentals",
    title: "انگلیسی از صفر",
    subtitle: "حروف، کلمات ساده و جمله‌های اول",
    longDescription:
      "این درس برای دانش‌آموزی است که تازه شروع کرده. با حروف، کلمه‌های ساده و جمله‌های کوتاه جلو می‌رویم تا بدون استرس انگلیسی را شروع کنی.",
    level: "مقدماتی",
    category: "speaking",
    mentor: "خانم سارا محمدی",
    mentorBio:
      "معلم انگلیسی کودکان و نوجوانان — بلد است درس را ساده و شاد توضیح بدهد.",
    mentorInitial: "س",
    rating: 4.9,
    reviews: 2148,
    students: 5400,
    durationHours: 18,
    lessons: 64,
    language: "فارسی + انگلیسی",
    lastUpdated: "آذر ۱۴۰۳",
    price: 850000,
    originalPrice: 1200000,
    bestseller: true,
    accent: "violet",
    glyph: "📘",
    outcomes: [
      { id: "o1", text: "خواندن و نوشتن حروف انگلیسی" },
      { id: "o2", text: "گفتن کلمه‌های روزمره" },
      { id: "o3", text: "ساختن جمله‌های کوتاه" },
      { id: "o4", text: "سلام و معرفی ساده به انگلیسی" },
      { id: "o5", text: "تمرین کوتاه هر روز بدون ترس" },
    ],
    requirements: [
      { id: "r1", text: "هیچ پیش‌نیازی نیست — از صفر شروع می‌کنیم." },
      { id: "r2", text: "یک گوشی یا تبلت برای دیدن ویدیو کافی است." },
    ],
    curriculum: [
      { id: "c1", title: "سلام و شروع", durationMinutes: 12, free: true },
      { id: "c2", title: "حروف الفبا", durationMinutes: 24, free: true },
      { id: "c3", title: "کلمه‌های خانه و مدرسه", durationMinutes: 28 },
      { id: "c4", title: "جمله‌های خیلی کوتاه", durationMinutes: 32 },
      { id: "c5", title: "عددها و رنگ‌ها", durationMinutes: 30 },
      { id: "c6", title: "تمرین حرف زدن", durationMinutes: 26 },
      { id: "c7", title: "مرور و بازی", durationMinutes: 45 },
    ],
  },
  "presentation-mastery": {
    id: "presentation-mastery",
    title: "گرامر آسان",
    subtitle: "قواعد مهم با مثال‌های کوتاه",
    longDescription:
      "گرامر را سخت و پیچیده نمی‌گوییم. با مثال‌های کوتاه و تمرین کم، قواعد مهم را یاد می‌گیری.",
    level: "متوسط",
    category: "presentation",
    mentor: "آقای رضا کریمی",
    mentorBio: "معلم گرامر و مکالمه — توضیحاتش کوتاه و واضح است.",
    mentorInitial: "ر",
    rating: 4.8,
    reviews: 1567,
    students: 3200,
    durationHours: 24,
    lessons: 82,
    language: "فارسی + انگلیسی",
    lastUpdated: "آبان ۱۴۰۳",
    price: 1200000,
    bestseller: true,
    accent: "pink",
    glyph: "✏️",
    outcomes: [
      { id: "o1", text: "زمان حال ساده" },
      { id: "o2", text: "سوال ساختن" },
      { id: "o3", text: "منفی کردن جمله" },
      { id: "o4", text: "استفاده از is / are / am" },
      { id: "o5", text: "تمرین با جمله‌های واقعی" },
    ],
    requirements: [
      { id: "r1", text: "کمی آشنایی با کلمات ساده انگلیسی." },
      { id: "r2", text: "دفترچه برای نوشتن مثال‌ها." },
    ],
    curriculum: [
      { id: "c1", title: "گرامر چیست؟ (ساده)", durationMinutes: 18, free: true },
      { id: "c2", title: "جمله درست بساز", durationMinutes: 30, free: true },
      { id: "c3", title: "زمان حال", durationMinutes: 35 },
      { id: "c4", title: "سوال بپرس", durationMinutes: 28 },
      { id: "c5", title: "اشتباه‌های رایج", durationMinutes: 32 },
      { id: "c6", title: "تمرین نهایی", durationMinutes: 50 },
    ],
  },
  "voice-training": {
    id: "voice-training",
    title: "شنیدن و تلفظ",
    subtitle: "گوش کردن و درست حرف زدن",
    longDescription:
      "یاد می‌گیری بهتر گوش بدهی و کلمات را درست تلفظ کنی — با تمرین‌های کوتاه و شاد.",
    level: "متوسط",
    category: "voice",
    mentor: "خانم نگار احمدی",
    mentorBio: "معلم تلفظ و شنیدن برای دانش‌آموزان.",
    mentorInitial: "ن",
    rating: 4.9,
    reviews: 932,
    students: 2100,
    durationHours: 16,
    lessons: 48,
    language: "فارسی + انگلیسی",
    lastUpdated: "آذر ۱۴۰۳",
    price: 980000,
    accent: "orchid",
    glyph: "🎧",
    outcomes: [
      { id: "o1", text: "تشخیص صداهای انگلیسی" },
      { id: "o2", text: "تلفظ واضح‌تر" },
      { id: "o3", text: "شنیدن جمله‌های کوتاه" },
      { id: "o4", text: "تکرار با اعتمادبه‌نفس" },
    ],
    requirements: [{ id: "r1", text: "هدفون یا اسپیکر برای شنیدن بهتر." }],
    curriculum: [
      { id: "c1", title: "گوش کردن آسان", durationMinutes: 20, free: true },
      { id: "c2", title: "صداهای مهم", durationMinutes: 25 },
      { id: "c3", title: "تلفظ کلمات", durationMinutes: 30 },
      { id: "c4", title: "جمله‌های کوتاه", durationMinutes: 28 },
    ],
  },
  "effective-communication": {
    id: "effective-communication",
    title: "کلمه‌های روزمره",
    subtitle: "واژگان مدرسه، خانه و دوستی",
    longDescription:
      "کلمه‌هایی که هر روز لازم داری: مدرسه، خانه، دوستان و بازی. با تصویر و تکرار یاد می‌گیری.",
    level: "مقدماتی",
    category: "communication",
    mentor: "آقای امیر حسینی",
    mentorBio: "معلم واژگان برای سطح دانش‌آموز.",
    mentorInitial: "ا",
    rating: 4.7,
    reviews: 1203,
    students: 2800,
    durationHours: 20,
    lessons: 70,
    language: "فارسی + انگلیسی",
    lastUpdated: "مهر ۱۴۰۳",
    price: 1100000,
    originalPrice: 1400000,
    accent: "blue",
    glyph: "💬",
    outcomes: [
      { id: "o1", text: "کلمه‌های مدرسه" },
      { id: "o2", text: "کلمه‌های خانه" },
      { id: "o3", text: "احساس‌ها و رنگ‌ها" },
      { id: "o4", text: "جمله با واژه‌های جدید" },
    ],
    requirements: [
      { id: "r1", text: "هیچ پیش‌نیاز سختی نیست." },
    ],
    curriculum: [
      { id: "c1", title: "کلمه‌های مدرسه", durationMinutes: 22, free: true },
      { id: "c2", title: "کلمه‌های خانه", durationMinutes: 34 },
      { id: "c3", title: "دوستان و بازی", durationMinutes: 28 },
      { id: "c4", title: "مرور با بازی", durationMinutes: 30 },
    ],
  },
  "leadership-speaking": {
    id: "leadership-speaking",
    title: "مکالمه شجاعانه",
    subtitle: "حرف زدن بدون ترس در کلاس",
    longDescription:
      "کمک می‌کند در کلاس و با دوستان به انگلیسی حرف بزنی — کوتاه، واضح و بدون ترس.",
    level: "پیشرفته",
    category: "speaking",
    mentor: "خانم سارا محمدی",
    mentorBio: "معلم مکالمه برای نوجوانان.",
    mentorInitial: "س",
    rating: 5.0,
    reviews: 645,
    students: 1500,
    durationHours: 28,
    lessons: 96,
    language: "فارسی + انگلیسی",
    lastUpdated: "دی ۱۴۰۳",
    price: 1650000,
    accent: "amber",
    glyph: "🗣️",
    outcomes: [
      { id: "o1", text: "معرفی خود به انگلیسی" },
      { id: "o2", text: "پرسیدن سوال ساده" },
      { id: "o3", text: "جواب دادن در کلاس" },
      { id: "o4", text: "کمتر ترسیدن از حرف زدن" },
    ],
    requirements: [
      { id: "r1", text: "کمی واژگان پایه." },
      { id: "r2", text: "بهتر است «انگلیسی از صفر» را دیده باشی." },
    ],
    curriculum: [
      { id: "c1", title: "اولین مکالمه", durationMinutes: 25, free: true },
      { id: "c2", title: "سوال و جواب", durationMinutes: 40 },
      { id: "c3", title: "در کلاس حرف بزن", durationMinutes: 38 },
      { id: "c4", title: "تمرین با دوست", durationMinutes: 45 },
    ],
  },
  storytelling: {
    id: "storytelling",
    title: "داستان‌های انگلیسی",
    subtitle: "خواندن داستان‌های کوتاه و شاد",
    longDescription:
      "با داستان‌های کوتاه و قشنگ، خواندن انگلیسی را تمرین می‌کنی و واژه‌های جدید یاد می‌گیری.",
    level: "متوسط",
    category: "voice",
    mentor: "خانم نگار احمدی",
    mentorBio: "معلم داستان و خواندن برای دانش‌آموزان.",
    mentorInitial: "ن",
    rating: 4.8,
    reviews: 814,
    students: 1900,
    durationHours: 22,
    lessons: 58,
    language: "فارسی + انگلیسی",
    lastUpdated: "آبان ۱۴۰۳",
    price: null,
    accent: "pink",
    glyph: "📖",
    outcomes: [
      { id: "o1", text: "خواندن داستان کوتاه" },
      { id: "o2", text: "فهمیدن معنی کلی" },
      { id: "o3", text: "یاد گرفتن واژه از داستان" },
      { id: "o4", text: "گفتن خلاصه خیلی ساده" },
    ],
    requirements: [{ id: "r1", text: "علاقه به داستان و کمی واژگان پایه." }],
    curriculum: [
      { id: "c1", title: "داستان اول (آسان)", durationMinutes: 20, free: true },
      { id: "c2", title: "واژه‌های داستان", durationMinutes: 32 },
      { id: "c3", title: "خواندن با صدای بلند", durationMinutes: 28 },
      { id: "c4", title: "داستان دوم", durationMinutes: 35 },
    ],
  },
};

/** Helper to get a detail by id (returns undefined if not found). */
export function getCourseDetail(id: string): CourseDetail | undefined {
  return courseDetails[id];
}

/** All detail ids (used for generateStaticParams). */
export const courseDetailIds = Object.keys(courseDetails);
