import type { CourseDetail } from "./types";

/**
 * Full course detail data for the checkout pages.
 *
 * `id` keys mirror the homepage catalog so the [id] route resolves cleanly.
 * Values are long-form Persian copy shown only on the detail page.
 */
export const courseDetails: Record<string, CourseDetail> = {
  fundamentals: {
    id: "fundamentals",
    title: "مبانی فن بیان",
    subtitle: "از صفر تا تسلط بر صحبت کردن در جمع",
    longDescription:
      "این دوره نقطه شروع ایده‌آل برای کسانی است که می‌خواهند با اصول اولیه فن بیان آشنا شوند. در طول دوره، با تکنیک‌های تنفسی، کنترل صدا، مدیریت استرس سخنرانی و ساختار یک ارائه مؤثر آشنا می‌شوید. هر درس با تمرین عملی همراه است تا مهارت‌ها در عمل نهادینه شوند.",
    level: "مقدماتی",
    category: "speaking",
    mentor: "دکتر سارا محمدی",
    mentorBio:
      "دکترای علوم ارتباطات با بیش از ۱۲ سال تجربه آموزش فن بیان و سخنرانی در دانشگاه‌ها و سازمان‌های معتبر.",
    mentorInitial: "س",
    rating: 4.9,
    reviews: 2148,
    students: 5400,
    durationHours: 18,
    lessons: 64,
    language: "فارسی",
    lastUpdated: "آذر ۱۴۰۳",
    price: 850000,
    originalPrice: 1200000,
    bestseller: true,
    accent: "violet",
    glyph: "🎤",
    outcomes: [
      { id: "o1", text: "کنترل کامل تنفس و صدا هنگام صحبت" },
      { id: "o2", text: "غلب بر ترس از سخنرانی در جمع" },
      { id: "o3", text: "ساختاردهی به یک ارائه روشن و مؤثر" },
      { id: "o4", text: "ارتباط چشمی و زبان بدن حرفه‌ای" },
      { id: "o5", text: "تمرین عملی با بازخورد مستقیم استاد" },
    ],
    requirements: [
      { id: "r1", text: "اشتیاق به یادگیری — هیچ پیش‌نیاز فنی وجود ندارد." },
      { id: "r2", text: "دسترسی به یک گوشی یا لپ‌تاپ برای تمرین ضبط." },
    ],
    curriculum: [
      { id: "c1", title: "مقدمه: چرا فن بیان مهم است؟", durationMinutes: 12, free: true },
      { id: "c2", title: "تکنیک‌های تنفسی دیافراگمی", durationMinutes: 24, free: true },
      { id: "c3", title: "کنترل تن صدا و لحن", durationMinutes: 28 },
      { id: "c4", title: "مدیریت استرس و اضطراب سخنرانی", durationMinutes: 32 },
      { id: "c5", title: "ساختار یک ارائه مؤثر", durationMinutes: 30 },
      { id: "c6", title: "زبان بدن و ارتباط چشمی", durationMinutes: 26 },
      { id: "c7", title: "تمرین عملی و بازخورد", durationMinutes: 45 },
    ],
  },
  "presentation-mastery": {
    id: "presentation-mastery",
    title: "استاد ارائه‌دهنده",
    subtitle: "ساخت و اجرای ارائه‌های تأثیرگذار",
    longDescription:
      "دوره‌ای جامع برای کسانی که می‌خواهند ارائه‌دهنده‌ای حرفه‌ای شوند. از طراحی اسلاید تا داستان‌گویی و مدیریت سوالات حضار، همه‌چیز را پوشش می‌دهد.",
    level: "متوسط",
    category: "presentation",
    mentor: "مهندس رضا کریمی",
    mentorBio:
      "مدرس و مشاور ارتباطات سازمانی با تجربه ارائه در کنفرانس‌های بین‌المللی.",
    mentorInitial: "ر",
    rating: 4.8,
    reviews: 1567,
    students: 3200,
    durationHours: 24,
    lessons: 82,
    language: "فارسی",
    lastUpdated: "آبان ۱۴۰۳",
    price: 1200000,
    bestseller: true,
    accent: "pink",
    glyph: "📊",
    outcomes: [
      { id: "o1", text: "طراحی اسلایدهای حرفه‌ای و مینیمال" },
      { id: "o2", text: "داستان‌گویی برای ارائه‌های فراموش‌نشدنی" },
      { id: "o3", text: "مدیریت سوالات دشوار حضار" },
      { id: "o4", text: "ارائه با اعتماد به نفس بالا" },
      { id: "o5", text: "ساخت دک خط‌نوشته (script) مؤثر" },
    ],
    requirements: [
      { id: "r1", text: "آشنایی اولیه با مفاهیم پایه ارائه." },
      { id: "r2", text: "دسترسی به PowerPoint یا ابزار مشابه." },
    ],
    curriculum: [
      { id: "c1", title: "اصول طراحی ارائه", durationMinutes: 18, free: true },
      { id: "c2", title: "ساختار داستان در ارائه", durationMinutes: 30, free: true },
      { id: "c3", title: "طراحی اسلاید حرفه‌ای", durationMinutes: 35 },
      { id: "c4", title: "تکنیک‌های داستان‌گویی", durationMinutes: 28 },
      { id: "c5", title: "مدیریت حضار و پرسش‌ها", durationMinutes: 32 },
      { id: "c6", title: "ارائه زنده و بازخورد", durationMinutes: 50 },
    ],
  },
  "voice-training": {
    id: "voice-training",
    title: "آواسازی حرفه‌ای صدا",
    subtitle: "تکنیک‌های تنفسی و رسایی صدای جذاب",
    longDescription:
      "صدای شما هویت شماست. در این دوره تکنیک‌های تخصصی برای زیباسازی، قدرتمندتر کردن و رسایی صدا را می‌آموزید.",
    level: "متوسط",
    category: "voice",
    mentor: "استاد نگار احمدی",
    mentorBio: "کارشناس آواسازی و گوینده حرفه‌ای با سال‌ها تجربه آموزشی.",
    mentorInitial: "ن",
    rating: 4.9,
    reviews: 932,
    students: 2100,
    durationHours: 16,
    lessons: 48,
    language: "فارسی",
    lastUpdated: "آذر ۱۴۰۳",
    price: 980000,
    accent: "orchid",
    glyph: "🎙️",
    outcomes: [
      { id: "o1", text: "تنفس دیافراگمی صحیح برای صدای قدرتمند" },
      { id: "o2", text: "افزایش رسایی و زیبایی صدا" },
      { id: "o3", text: "حذف عادات بد گفتاری" },
      { id: "o4", text: "تنوع لحن برای جذابیت بیشتر" },
    ],
    requirements: [{ id: "r1", text: "پیش‌نیازی نیاز نیست — علاقه کافی است." }],
    curriculum: [
      { id: "c1", title: "آناتومی صدا و تنفس", durationMinutes: 20, free: true },
      { id: "c2", title: "تمرینات تنفسی روزانه", durationMinutes: 25 },
      { id: "c3", title: "رسایی و طنین صدا", durationMinutes: 30 },
      { id: "c4", title: "تنوع لحن و بیان احساس", durationMinutes: 28 },
    ],
  },
  "effective-communication": {
    id: "effective-communication",
    title: "ارتباط مؤثر در محیط کار",
    subtitle: "مهارت‌های کلامی برای پیشرفت شغلی",
    longDescription:
      "ارتباط مؤثر، کلید پیشرفت شغلی است. این دوره شما را برای مذاکره، مدیریت جلسات و ارتباط با همکاران آماده می‌کند.",
    level: "متوسط",
    category: "communication",
    mentor: "دکتر امیر حسینی",
    mentorBio: "مشاور ارتباطات سازمانی و مدرس مهارت‌های نرم.",
    mentorInitial: "ا",
    rating: 4.7,
    reviews: 1203,
    students: 2800,
    durationHours: 20,
    lessons: 70,
    language: "فارسی",
    lastUpdated: "مهر ۱۴۰۳",
    price: 1100000,
    originalPrice: 1400000,
    accent: "blue",
    glyph: "🤝",
    outcomes: [
      { id: "o1", text: "تکنیک‌های مذاکره تأثیرگذار" },
      { id: "o2", text: "مدیریت جلسات کاری" },
      { id: "o3", text: "ارتباط مؤثر با همکاران و مدیران" },
      { id: "o4", text: "گفتگوی سازنده در شرایط دشوار" },
    ],
    requirements: [
      { id: "r1", text: "تجربه کاری در یک محیط سازمانی." },
    ],
    curriculum: [
      { id: "c1", title: "اصول ارتباط مؤثر", durationMinutes: 22, free: true },
      { id: "c2", title: "تکنیک‌های مذاکره", durationMinutes: 34 },
      { id: "c3", title: "مدیریت جلسات", durationMinutes: 28 },
      { id: "c4", title: "گفتگوی دشوار", durationMinutes: 30 },
    ],
  },
  "leadership-speaking": {
    id: "leadership-speaking",
    title: "سخنوری رهبران",
    subtitle: "هوش هیجانی و اقناع در رهبری",
    longDescription:
      "برای رهبران و مدیرانی که می‌خواهند کلامشان الهام‌بخش باشد. تلفیق فن بیان، هوش هیجانی و فن اقناع.",
    level: "پیشرفته",
    category: "speaking",
    mentor: "دکتر سارا محمدی",
    mentorBio: "دکترای علوم ارتباطات با بیش از ۱۲ سال تجربه آموزشی.",
    mentorInitial: "س",
    rating: 5.0,
    reviews: 645,
    students: 1500,
    durationHours: 28,
    lessons: 96,
    language: "فارسی",
    lastUpdated: "دی ۱۴۰۳",
    price: 1650000,
    accent: "amber",
    glyph: "👑",
    outcomes: [
      { id: "o1", text: "سخنرانی الهام‌بخش رهبرانه" },
      { id: "o2", text: "کاربرد هوش هیجانی در ارتباط" },
      { id: "o3", text: "فن اقناع تأثیرگذار" },
      { id: "o4", text: "هدایت تیم با کلام" },
    ],
    requirements: [
      { id: "r1", text: "تجربه مدیریت یا رهبری تیم." },
      { id: "r2", text: "پیشنهاد می‌شود ابتدا دوره مبانی فن بیان را گذرانده باشید." },
    ],
    curriculum: [
      { id: "c1", title: "بیان رهبرانه", durationMinutes: 25, free: true },
      { id: "c2", title: "هوش هیجانی در ارتباط", durationMinutes: 40 },
      { id: "c3", title: "فن اقناع", durationMinutes: 38 },
      { id: "c4", title: "سخنرانی الهام‌بخش", durationMinutes: 45 },
    ],
  },
  storytelling: {
    id: "storytelling",
    title: "هنر داستان‌گویی",
    subtitle: "ساختن روایت‌هایی که می‌مانند",
    longDescription:
      "داستان‌گویی قدرتمندترین ابزار ارتباطی است. یاد بگیرید چطور روایت‌هایی بسازید که در ذهن و قلب مخاطب بنشینند.",
    level: "حرفه‌ای",
    category: "presentation",
    mentor: "استاد نگار احمدی",
    mentorBio: "کارشناس آواسازی و داستان‌گویی حرفه‌ای.",
    mentorInitial: "ن",
    rating: 4.8,
    reviews: 814,
    students: 1900,
    durationHours: 22,
    lessons: 58,
    language: "فارسی",
    lastUpdated: "آبان ۱۴۰۳",
    price: null,
    accent: "pink",
    glyph: "📖",
    outcomes: [
      { id: "o1", text: "ساختار روایت مؤثر" },
      { id: "o2", text: "شخصیت‌پردازی جذاب" },
      { id: "o3", text: "تأثیرگذاری احساسی بر مخاطب" },
      { id: "o4", text: "داستان‌گویی در ارائه‌ها" },
    ],
    requirements: [{ id: "r1", text: "علاقه به داستان و روایت." }],
    curriculum: [
      { id: "c1", title: "اصول داستان‌گویی", durationMinutes: 20, free: true },
      { id: "c2", title: "ساختار روایت", durationMinutes: 32 },
      { id: "c3", title: "شخصیت‌پردازی", durationMinutes: 28 },
      { id: "c4", title: "داستان در ارائه", durationMinutes: 35 },
    ],
  },
};

/** Helper to get a detail by id (returns undefined if not found). */
export function getCourseDetail(id: string): CourseDetail | undefined {
  return courseDetails[id];
}

/** All detail ids (used for generateStaticParams). */
export const courseDetailIds = Object.keys(courseDetails);
